name: Build, test and Deploy DEV BE

on:
  push:
    branches:
      - Develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RepoA
        uses: actions/checkout@v2
        repository: Proyecto-DevOps-Gonzalo-Gaston/Proyecto_BackEnd_Payments

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8' 
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

   test:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8' 
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Run Tests with Maven
      run: mvn test
