name: Build, Test and Deploy on Develop BE 
on:
  push:
    branches:
      - Develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'  
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Install Maven dependencies
        run: mvn dependency:resolve

      - name: Build with Maven
        run: mvn clean install
      
      - name: Build package
        run: mvn clean package
      
  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'  
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Run Tests with Maven
      run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    - name:
      run: docker build --build-arg JAR_FILE=(RUTA A JAR FILE) -t payments-service-example:1 .